IMAGE_FOLDER="/usr/share/openmediavault/customimages/default/"
LOGIN_IMAGE="login.jpg"
LOGIN_BLENDMODE="hard-light"
STANDBY_IMAGE="standby.jpg"
STANDBY_BLENDMODE="luminosity"
SHUTDOWN_IMAGE="shutdown.jpg"
SHUTDOWN_BLENDMODE="luminosity"
