LOGIN_IMAGE="/usr/share/openmediavault/customimages/default/login.jpg"
LOGIN_BLENDMODE="hard-light"
STANDBY_IMAGE="/usr/share/openmediavault/customimages/default/standby.jpg"
STANDBY_BLENDMODE="luminosity"
SHUTDOWN_IMAGE="/usr/share/openmediavault/customimages/default/shutdown.jpg"
SHUTDOWN_BLENDMODE="luminosity"
