LOGIN_IMAGE="/var/www/openmediavault/assets/images/login.jpg"
LOGIN_BLENDMODE="hard-light"
STANDBY_IMAGE="/var/www/openmediavault/assets/images/standby.jpg"
STANDBY_BLENDMODE="luminosity"
SHUTDOWN_IMAGE="/var/www/openmediavault/assets/images/shutdown.jpg"
SHUTDOWN_BLENDMODE="luminosity"
