#!/bin/sh
set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
  configure)
    # Datenbank initialisieren
    omv_config_update "/config/services/customimages"
    # Confdb-Eintrag anlegen
    if [ -x /usr/share/openmediavault/confdb/create.d/conf.service.customimages.sh ]; then
      /usr/share/openmediavault/confdb/create.d/conf.service.customimages.sh
    fi
    # engined neu starten
    monit restart omv-engined || true
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
exit 0
