#!/bin/sh
set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
  configure)
    # Activate trigger to rebuild workbench configuration files.
    dpkg-trigger update-workbench
    # Initialize and migrate configuration database.
    echo "Updating configuration database ..."
    omv-confdbadm create "conf.system.customthemes"
    # Deploy the configuration for autoshutdown services.
    echo "Deploying customthemes service configuration ..."
    LC_ALL=C.UTF-8 omv-salt deploy run --no-color --quiet customthemes
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
exit 0
