#!/bin/bash

grep -q 'patchomv' "/var/www/openmediavault/index.html" && change=no || change=yes
if [ "$change" = "yes" ]; then
    sudo sed -i -e 's|</head>|<!--patchomv--><link rel="stylesheet" href="/theme.css"></head>|' /var/www/openmediavault/index.html
fi


exit 0